### PR TITLE
feat: add help text modal and github link

### PR DESCRIPTION
**Pull request by dbluhm**
This PR adds a help text modal and a link to github. The initial commit contains just placeholder text. We'll fill this out before merging. @TelegramSam

### CODE REVIEW

**Comment by dbluhm** [comment]
A couple of screenshots.
Screenshot from 2023-10-06 14-26-59
Screenshot from 2023-10-06 14-26-47

**Review by frostyfrog — APPROVED** [review]
LGTM

**Comment by dbluhm** [comment]
I was intending to leave this one open until Sam got the real help text in lol. Should have opened it as a draft to communicate that better. Thanks though!

**Comment by frostyfrog** [comment]
:sweat_smile: Whoops, sorry about that. I had seen it discussed in the issue, so I thought it was ready.

**Pull request merged**
